version: '3.8'

services:
  # --- Banco de Dados ---
  db:
    image: postgres:15-alpine
    container_name: winthor_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # --- Backend (Sua Aplicação) ---

  backend:
    build: 
      context: ./backend # Aponta para a pasta do backend
    container_name: winthor_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app # Para hot-reload durante o desenvolvimento

  frontend:
    build:
      context: ./frontend # Aponta para a pasta do frontend
    container_name: winthor_frontend
    restart: always
    ports:
      - "80:80" # Porta Web padrão
    depends_on:
      - backend


volumes:
  postgres_data: